### ISSUE TITLE
Encoding query parameters

### ISSUE THREAD

**Issue by JMPerez** [loverajoel/spotify-js#13]
I was testing today your MagicPlaylist site and I realised it's not handling some special characters properly when searching.

A search query like "Maná" triggers the following request:
https://api.spotify.com/v1/search?type=track&q=Man%E1&limit=1&market=US

however, it should trigger this one instead:
https://api.spotify.com/v1/search?type=track&q=Man%C3%A1&limit=1&market=US

The query parameters need to be url encoded here:
https://github.com/loverajoel/spotify-sdk/blob/master/src/handlers/TrackHandler.js#L24

Let me know if you think this is a valid issue and I can work myself on a fix.

**Comment by loverajoel** [comment]
Yes, this is a issue.
The solution should contemplate all endpoints when text can be send how parameter, what do you think add the encode in the Client?

**Comment by loverajoel** [comment]
Pr by @JMPerez  https://github.com/loverajoel/spotify-sdk/pull/14
