### ISSUE TITLE
Implement saved-track-object and saved-album-object?

### ISSUE THREAD

**Issue by schwamic** [loverajoel/spotify-js#18]
Hey,
i saw you implemented track-objects and album-objects but is it also possible to get saved-track-objects and saved-album-objects?

thx

**Comment by loverajoel** [comment]
Hey, sorry by the delay, I'm with a lot of work.
Can you add more info?

**Comment by emiprandi** [comment]
Hi, i just sent a PR adding support to user's saved tracks and albums.

https://github.com/loverajoel/spotify-sdk/pull/19

**Comment by loverajoel** [comment]
PR merged. Thanks @emiprandi 
![](https://media4.giphy.com/media/kHrWKmyLICrCM/200_s.gif)
